import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/app/Components/footer";
import Header from "@/app/Components/header";
import { fetchApi } from "./utills/fetch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getSession() {
  const res = await fetchApi("/api/users/me")
  if(res) {
    if(res.status == 200) {
      return res.data
    } else {
      return null
    }
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="bg-gray-200 min-h-screen grid grid-rows-[auto_1fr_auto]">
          <Header user={user} />
            {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}